@startuml

skinparam class {
  BackgroundColor<<Impl>> #EEEEFF
  BorderColor<<Impl>> black
}

package "4. Run-time Dependencies" {

    package "3. Compile-time Dependencies for API usage" #fffff0 {

        package "1. All-In-One" {

            interface ApiType {
                someMethod()
            }

            class "ImplType" <<Impl>>

            ApiType *--right-- ImplType
        }

        package "2a. ApiDependencies" {

            class SomeDependency

            ApiType --* SomeDependency
        }

        package "2b. ImplDependencies" {

            class SomeImplDependency1 <<Impl>>
            class SomeImplDependency2 <<Impl>>

            ImplType --* SomeImplDependency1
            ImplType --* SomeImplDependency2
        }
    }
}

class "Calling Client"
ApiType <..down. "Calling Client"

@enduml